import hero1 from "@/assets/hero-1.jpg";
import hero1m from "@/assets/hero-1-mobile.jpg";
import hero2 from "@/assets/hero-2.jpg";
import hero2m from "@/assets/hero-2-mobile.jpg";
import hero3 from "@/assets/hero-3.jpg";
import hero3m from "@/assets/hero-3-mobile.jpg";
import showPoints from "@/assets/show-points-miles.jpg";
import showTelugu from "@/assets/show-telugu-space.jpg";
import showKaushik from "@/assets/show-kaushik.jpg";
import showSwati from "@/assets/show-swati.jpg";
import showCurious from "@/assets/show-curious.jpg";
import posterPoints from "@/assets/poster-points-miles.jpg";
import posterTelugu from "@/assets/poster-telugu-space.jpg";
import posterKaushik from "@/assets/poster-kaushik.jpg";
import posterSwati from "@/assets/poster-swati.jpg";
import posterCurious from "@/assets/poster-curious.jpg";
import editPost from "@/assets/edit-post.jpg";
import editCreator from "@/assets/edit-creator.jpg";
import editBrand from "@/assets/edit-brand.jpg";
import person1 from "@/assets/person-1.jpg";
import person2 from "@/assets/person-2.jpg";
import person3 from "@/assets/person-3.jpg";

import { topTenDefaults } from "./top-ten-defaults";
import type { SiteContent } from "./types";

export const images = {
  hero1,
  hero1m,
  hero2,
  hero2m,
  hero3,
  hero3m,
  showPoints,
  showTelugu,
  showKaushik,
  showSwati,
  showCurious,
  posterPoints,
  posterTelugu,
  posterKaushik,
  posterSwati,
  posterCurious,
  editPost,
  editCreator,
  editBrand,
  person1,
  person2,
  person3,
};

const YT = "https://www.youtube.com/@kathanikamedia";

export const defaultContent: SiteContent = {
  topTenChannels: topTenDefaults,
  heroSlides: [
    {
      id: "hero-1",
      active: true,
      order: 1,
      eyebrow: "Kathanika Original",
      title: "The Great Indian Points & Miles Show",
      description: "Conversations transformed into an original media property.",
      image: hero1,
      mobileImage: hero1m,
      youtubeUrl: YT,
      exploreUrl: "/work",
      primaryCta: "Watch Now",
      secondaryCta: "Explore Show",
    },
    {
      id: "hero-2",
      active: true,
      order: 2,
      eyebrow: "Kathanika Original",
      title: "We build media properties",
      description:
        "Kathanika builds original IPs and content ecosystems for brands, creators and leaders.",
      image: hero2,
      mobileImage: hero2m,
      youtubeUrl: YT,
      exploreUrl: "/work",
      primaryCta: "Watch Now",
      secondaryCta: "Explore Kathanika",
    },
    {
      id: "hero-3",
      active: true,
      order: 3,
      eyebrow: "Production",
      title: "Stories worth building. Audiences worth owning.",
      description: "End-to-end production across every major Indian city.",
      image: hero3,
      mobileImage: hero3m,
      youtubeUrl: YT,
      exploreUrl: "/work",
      primaryCta: "Watch Now",
      secondaryCta: "See the Work",
    },
  ],
  topFive: [
    {
      id: "t5-1",
      active: true,
      order: 1,
      rank: 1,
      title: "The Great Indian Points & Miles Show",
      category: "Original IP",
      badge: "Kathanika Original",
      description: "Travel, points and the economics of flying better.",
      thumbnail: showPoints,
      youtubeUrl: YT,
    },
    {
      id: "t5-2",
      active: true,
      order: 2,
      rank: 2,
      title: "Curious Nikhil & Prudvi Show",
      category: "Original IP",
      badge: "Popular",
      description: "Two hosts, one question at a time.",
      thumbnail: showCurious,
      youtubeUrl: YT,
    },
    {
      id: "t5-3",
      active: true,
      order: 3,
      rank: 3,
      title: "Telugu Space",
      category: "Culture",
      badge: "Featured",
      description: "Telugu culture, told with contemporary craft.",
      thumbnail: showTelugu,
      youtubeUrl: YT,
    },
    {
      id: "t5-4",
      active: true,
      order: 4,
      rank: 4,
      title: "Kaushik & Co.",
      category: "Business",
      badge: "New Release",
      description: "Founders on the decisions that actually mattered.",
      thumbnail: showKaushik,
      youtubeUrl: YT,
    },
    {
      id: "t5-5",
      active: true,
      order: 5,
      rank: 5,
      title: "A Dialogue with Swati",
      category: "Interview",
      badge: "Brand Story",
      description: "Long-form conversations, unhurried and unfiltered.",
      thumbnail: showSwati,
      youtubeUrl: YT,
    },
  ],
  originalIps: [
    {
      id: "ip-1",
      active: true,
      order: 1,
      slug: "points-and-miles",
      title: "The Great Indian Points & Miles Show",
      category: "Travel · Original IP",
      description:
        "A show built from a niche community conversation into a full media property — episodes, clips, newsletters and a loyal, high-intent audience.",
      poster: posterPoints,
      still: showPoints,
      youtubeUrl: YT,
      socialUrl: "https://instagram.com/kathanikamedia",
      stats: [
        { label: "Episodes", value: "40+" },
        { label: "Monthly reach", value: "1.2 Cr" },
        { label: "Formats", value: "Long-form + Reels" },
      ],
    },
    {
      id: "ip-2",
      active: true,
      order: 2,
      slug: "telugu-space",
      title: "Telugu Space",
      category: "Culture · Original IP",
      description:
        "Telugu stories, language and culture presented with the production value of a streaming title.",
      poster: posterTelugu,
      still: showTelugu,
      youtubeUrl: YT,
      socialUrl: "https://instagram.com/kathanikamedia",
      stats: [
        { label: "Episodes", value: "25+" },
        { label: "Languages", value: "Telugu · English" },
        { label: "Format", value: "Studio" },
      ],
    },
    {
      id: "ip-3",
      active: true,
      order: 3,
      slug: "kaushik-and-co",
      title: "Kaushik & Co.",
      category: "Business · Original IP",
      description:
        "Founders and operators in conversation about the decisions behind the headlines.",
      poster: posterKaushik,
      still: showKaushik,
      youtubeUrl: YT,
      socialUrl: "https://linkedin.com/company/kathanikamedia",
      stats: [
        { label: "Episodes", value: "18+" },
        { label: "Guests", value: "Founders · CEOs" },
        { label: "Format", value: "Long-form" },
      ],
    },
    {
      id: "ip-4",
      active: true,
      order: 4,
      slug: "a-dialogue-with-swati",
      title: "A Dialogue with Swati",
      category: "Interview · Original IP",
      description: "Unhurried, single-camera conversations that let the subject breathe.",
      poster: posterSwati,
      still: showSwati,
      youtubeUrl: YT,
      socialUrl: "https://instagram.com/kathanikamedia",
      stats: [
        { label: "Episodes", value: "12+" },
        { label: "Runtime", value: "45–60 min" },
        { label: "Format", value: "Interview" },
      ],
    },
    {
      id: "ip-5",
      active: true,
      order: 5,
      slug: "curious-nikhil-and-prudvi",
      title: "Curious Nikhil & Prudvi Show",
      category: "Entertainment · Original IP",
      description: "A curiosity-led format built for clips, community and repeat viewing.",
      poster: posterCurious,
      still: showCurious,
      youtubeUrl: YT,
      socialUrl: "https://instagram.com/kathanikamedia",
      stats: [
        { label: "Episodes", value: "30+" },
        { label: "Clips", value: "500+" },
        { label: "Format", value: "Studio + Field" },
      ],
    },
  ],
  episodes: [
    {
      id: "ep-1",
      ipId: "ip-1",
      label: "Featured Episode",
      title: "How to fly business class on an economy budget",
      thumbnail: showPoints,
      youtubeUrl: YT,
      duration: "48 min",
    },
    {
      id: "ep-2",
      ipId: "ip-1",
      label: "Popular Episode",
      title: "The credit card game, explained end to end",
      thumbnail: hero1,
      youtubeUrl: YT,
      duration: "52 min",
    },
    {
      id: "ep-3",
      ipId: "ip-1",
      label: "Latest Episode",
      title: "Award seats: what still works in 2026",
      thumbnail: posterPoints,
      youtubeUrl: YT,
      duration: "39 min",
    },
    {
      id: "ep-4",
      ipId: "ip-3",
      label: "Featured Episode",
      title: "Building a category before the category exists",
      thumbnail: showKaushik,
      youtubeUrl: YT,
      duration: "57 min",
    },
    {
      id: "ep-5",
      ipId: "ip-5",
      label: "Featured Episode",
      title: "Why curiosity out-performs cleverness",
      thumbnail: showCurious,
      youtubeUrl: YT,
      duration: "41 min",
    },
  ],
  portfolio: [
    {
      id: "p-1",
      active: true,
      order: 1,
      title: "The Great Indian Points & Miles Show",
      client: "Kathanika Media",
      category: "Original IPs",
      description: "A niche conversation turned into an owned media property.",
      cover: showPoints,
      youtubeUrl: YT,
      instagramUrl: "",
      projectUrl: "/work",
      featured: true,
      size: "wide",
    },
    {
      id: "p-2",
      active: true,
      order: 2,
      title: "Founder Podcast Series",
      client: "Kaushik & Co.",
      category: "Podcasts",
      description: "Studio build, multi-cam production and full distribution.",
      cover: showKaushik,
      youtubeUrl: YT,
      instagramUrl: "",
      projectUrl: "",
      featured: true,
      size: "tall",
    },
    {
      id: "p-3",
      active: true,
      order: 3,
      title: "Clinic to Camera",
      client: "Leading Hyderabad Hospital",
      category: "Healthcare",
      description: "Monthly content systems for practising doctors.",
      cover: editBrand,
      youtubeUrl: "",
      instagramUrl: "https://instagram.com/kathanikamedia",
      projectUrl: "",
      featured: false,
      size: "regular",
    },
    {
      id: "p-4",
      active: true,
      order: 4,
      title: "Creator Incubation Slate",
      client: "Kathanika Creators",
      category: "Personal Brands",
      description: "From first idea to a repeatable publishing engine.",
      cover: editCreator,
      youtubeUrl: "",
      instagramUrl: "https://instagram.com/kathanikamedia",
      projectUrl: "/creators",
      featured: false,
      size: "regular",
    },
    {
      id: "p-5",
      active: true,
      order: 5,
      title: "Culture Reels Slate",
      client: "Telugu Space",
      category: "Reels",
      description: "Short-form built from long-form, at volume.",
      cover: showTelugu,
      youtubeUrl: YT,
      instagramUrl: "",
      projectUrl: "",
      featured: false,
      size: "wide",
    },
    {
      id: "p-6",
      active: true,
      order: 6,
      title: "Post Production Systems",
      client: "Multi-brand",
      category: "Brand Content",
      description: "Edit, grade and delivery pipelines for always-on content.",
      cover: editPost,
      youtubeUrl: "",
      instagramUrl: "",
      projectUrl: "",
      featured: false,
      size: "regular",
    },
    {
      id: "p-7",
      active: true,
      order: 7,
      title: "City Rooftop Campaign",
      client: "Shelter Electronics",
      category: "Campaigns",
      description: "A single shoot day cut into a quarter of content.",
      cover: hero3,
      youtubeUrl: "",
      instagramUrl: "",
      projectUrl: "",
      featured: true,
      size: "wide",
    },
    {
      id: "p-8",
      active: true,
      order: 8,
      title: "Long-form Interview Slate",
      client: "A Dialogue with Swati",
      category: "YouTube",
      description: "Interview craft with cinematic single-camera coverage.",
      cover: showSwati,
      youtubeUrl: YT,
      instagramUrl: "",
      projectUrl: "",
      featured: false,
      size: "tall",
    },
  ],
  services: [
    { id: "s-1", active: true, order: 1, title: "Content as a Service", description: "Strategy, formats and recurring content built around a clear audience and business objective." },
    { id: "s-2", active: true, order: 2, title: "Reels as a Service", description: "Short-form storytelling designed for discovery, recall and repeat viewing." },
    { id: "s-3", active: true, order: 3, title: "Podcast as a Service", description: "Concept, studio production, editing, packaging and distribution for long-form conversations." },
    { id: "s-4", active: true, order: 4, title: "YouTube as a Service", description: "Channel strategy, formats, packaging and publishing systems built for consistent growth." },
    { id: "s-5", active: true, order: 5, title: "End-to-End Production", description: "From pre-production to final delivery: crew, direction, cameras, sound, art and post-production." },
    { id: "s-6", active: true, order: 6, title: "Social Media Management", description: "Editorial calendars, publishing, community management and platform-native creative." },
    { id: "s-7", active: true, order: 7, title: "Distribution & Audience Growth", description: "Packaging, publishing and distribution designed to put the right content in front of the right audience." },
    { id: "s-8", active: true, order: 8, title: "IP Development", description: "Turn a content idea into a recognisable media property with a clear audience, format and identity." },
    { id: "s-9", active: true, order: 9, title: "Brand Building", description: "Build a distinct brand narrative, content language and media presence that stays consistent across platforms." },
    { id: "s-10", active: true, order: 10, title: "Personal Branding", description: "Personal brand strategy and content systems for founders, doctors, CEOs and investors." },
  ],
  brands: [
    { id: "b-1", active: true, order: 1, name: "Spotify", note: "Content collaboration" },
    { id: "b-2", active: true, order: 2, name: "HackerRank", note: "Brand content" },
    { id: "b-3", active: true, order: 3, name: "Asian Paints", note: "Campaign content" },
    { id: "b-4", active: true, order: 4, name: "Shelter Electronics", note: "Production" },
  ],
  testimonials: [
    {
      id: "tm-1",
      active: true,
      order: 1,
      quote:
        "They did not hand us a content calendar. They handed us a show — and the audience came with it.",
      name: "Ananya Rao",
      designation: "Founder",
      organisation: "Consumer brand, Hyderabad",
      photo: person1,
    },
    {
      id: "tm-2",
      active: true,
      order: 2,
      quote:
        "Patients now arrive already knowing how I think. That is what the content did for the practice.",
      name: "Dr. Vikram Menon",
      designation: "Consultant Surgeon",
      organisation: "Multi-speciality hospital",
      photo: person2,
    },
    {
      id: "tm-3",
      active: true,
      order: 3,
      quote: "I had ideas. Kathanika gave them a format, a schedule and an audience.",
      name: "Prudvi Reddy",
      designation: "Creator",
      organisation: "Kathanika Creators",
      photo: person3,
    },
  ],
  enquiries: [],
  social: {
    youtube: YT,
    instagram: "https://instagram.com/kathanikamedia",
    linkedin: "https://linkedin.com/company/kathanikamedia",
  },
  settings: {
    whatsappNumber: "919063854291",
    email: "kathanikamedia@gmail.com",
    phone: "+91 90638 54291",
    addressLine: "Kathanika Media Office, 3rd Floor, Opp. Swathi Multi-speciality, Road No. 10, Gouri Shankar Nagar Colony, Banjara Hills, Hyderabad, Telangana 500034",
    mapsUrl: "https://maps.google.com/?q=Kathanika+Media+Office+Road+No+10+Gouri+Shankar+Nagar+Colony+Banjara+Hills+Hyderabad+Telangana+500034",
    cities: ["Hyderabad", "Bengaluru", "Chennai", "Mumbai", "Delhi"],
    metrics: [
      { value: "8–12", label: "Active content channels" },
      { value: "10+", label: "Brands every month" },
      { value: "3+ Cr", label: "Monthly content reach" },
      { value: "10+", label: "Doctors worked with monthly" },
      { value: "1.5+ yrs", label: "Of continuous execution" },
      { value: "5", label: "Major Indian cities" },
    ],
  },
};